/**
 * Reactive State Store for SentinelAI Threat Detection Platform
 * Fully integrated with real REST backend API and Indian Personas:
 * Admin: Arjun Sharma
 * Employees: Ananya Rao, Rahul Kumar, Priya Nair, Vikram Reddy, Sneha Iyer
 */

import {
  ActivityEvent,
  ActivityEventType,
  CorporateFile,
  RiskAssessment,
  SecurityIncident,
  User,
} from '../types/threat';
import { generateSyntheticEnrolledEmbedding, verifyFace } from './faceVerification';
import { runInferencePipeline } from './mlEngine';
import {
  activityApi,
  adminApi,
  faceApi,
  hardwareApi,
  incidentsApi,
  simulateApi,
  usersApi,
  filesApi,
} from './api';

// Avatars generated by AI Studio
const AVATAR_SECOPS = '/src/assets/images/avatar_secops_lead_1790179950264.jpg';
const AVATAR_ANANYA = '/src/assets/images/avatar_engineer_elena_1790179962515.jpg';
const AVATAR_VIKRAM = '/src/assets/images/avatar_contractor_marcus_1790179973579.jpg';

// Initial Indian Personas (Section 19)
export const INITIAL_USERS: User[] = [
  {
    id: 'usr_arjun_1',
    name: 'Arjun Sharma',
    email: 'arjun.sharma@cyberdefense.in',
    role: 'admin',
    department: 'Information Security & SecOps',
    title: 'Lead SecOps Administrator',
    avatarUrl: AVATAR_SECOPS,
    isRestricted: false,
    isTerminated: false,
    enrolledFaceEmbedding: generateSyntheticEnrolledEmbedding('arjun_sharma_admin_baseline'),
    lastActive: new Date().toISOString(),
    currentRiskScore: 6,
    currentRiskBand: 'LOW',
    baseline: {
      userId: 'usr_arjun_1',
      typicalLoginHourStart: 8,
      typicalLoginHourEnd: 20,
      knownIps: ['192.168.1.10', '10.0.0.1'],
      avgDailyDownloads: 4,
      stdDailyDownloads: 1.5,
      typicalFileCategories: ['Internal', 'Confidential', 'Restricted_Vault'],
      usbAuthorized: true,
      baselineAnomalyScore: 0.05,
    },
  },
  {
    id: 'usr_ananya_2',
    name: 'Ananya Rao',
    email: 'ananya.rao@cyberdefense.in',
    role: 'employee',
    department: 'AI Systems & Engineering',
    title: 'Senior ML Platform Engineer',
    avatarUrl: AVATAR_ANANYA,
    isRestricted: false,
    isTerminated: false,
    enrolledFaceEmbedding: generateSyntheticEnrolledEmbedding('ananya_rao_enrolled_face'),
    lastActive: new Date(Date.now() - 5 * 60000).toISOString(),
    currentRiskScore: 14,
    currentRiskBand: 'LOW',
    baseline: {
      userId: 'usr_ananya_2',
      typicalLoginHourStart: 9,
      typicalLoginHourEnd: 18,
      knownIps: ['192.168.1.42', '10.0.4.15'],
      avgDailyDownloads: 3,
      stdDailyDownloads: 1.0,
      typicalFileCategories: ['Public', 'Internal'],
      usbAuthorized: false,
      baselineAnomalyScore: 0.08,
    },
  },
  {
    id: 'usr_rahul_3',
    name: 'Rahul Kumar',
    email: 'rahul.kumar@cyberdefense.in',
    role: 'employee',
    department: 'Core Platform',
    title: 'Full-Stack Cloud Architect',
    avatarUrl: undefined,
    isRestricted: false,
    isTerminated: false,
    enrolledFaceEmbedding: generateSyntheticEnrolledEmbedding('rahul_kumar_face_profile'),
    lastActive: new Date(Date.now() - 25 * 60000).toISOString(),
    currentRiskScore: 18,
    currentRiskBand: 'LOW',
    baseline: {
      userId: 'usr_rahul_3',
      typicalLoginHourStart: 10,
      typicalLoginHourEnd: 19,
      knownIps: ['192.168.1.88', '10.0.4.22'],
      avgDailyDownloads: 5,
      stdDailyDownloads: 2.0,
      typicalFileCategories: ['Public', 'Internal'],
      usbAuthorized: false,
      baselineAnomalyScore: 0.12,
    },
  },
  {
    id: 'usr_priya_4',
    name: 'Priya Nair',
    email: 'priya.nair@cyberdefense.in',
    role: 'employee',
    department: 'Data Engineering',
    title: 'Staff Data Infrastructure Engineer',
    avatarUrl: undefined,
    isRestricted: false,
    isTerminated: false,
    enrolledFaceEmbedding: generateSyntheticEnrolledEmbedding('priya_nair_face_profile'),
    lastActive: new Date(Date.now() - 15 * 60000).toISOString(),
    currentRiskScore: 12,
    currentRiskBand: 'LOW',
    baseline: {
      userId: 'usr_priya_4',
      typicalLoginHourStart: 9,
      typicalLoginHourEnd: 17,
      knownIps: ['192.168.1.105'],
      avgDailyDownloads: 6,
      stdDailyDownloads: 2.0,
      typicalFileCategories: ['Internal'],
      usbAuthorized: false,
      baselineAnomalyScore: 0.07,
    },
  },
  {
    id: 'usr_vikram_5',
    name: 'Vikram Reddy',
    email: 'vikram.reddy@cyberdefense.in',
    role: 'employee',
    department: 'Cloud Infrastructure',
    title: 'External DevOps Contractor',
    avatarUrl: AVATAR_VIKRAM,
    isRestricted: false,
    isTerminated: false,
    enrolledFaceEmbedding: null, // Deliberately null to test missing profile / Scenario 3
    lastActive: new Date(Date.now() - 40 * 60000).toISOString(),
    currentRiskScore: 24,
    currentRiskBand: 'LOW',
    baseline: {
      userId: 'usr_vikram_5',
      typicalLoginHourStart: 8,
      typicalLoginHourEnd: 17,
      knownIps: ['10.0.4.15'],
      avgDailyDownloads: 2,
      stdDailyDownloads: 1.0,
      typicalFileCategories: ['Internal'],
      usbAuthorized: false,
      baselineAnomalyScore: 0.15,
    },
  },
];

export const INITIAL_FILES: CorporateFile[] = [
  {
    id: 'file_arch_1',
    name: 'Engineering_Architecture_2026.pdf',
    category: 'Internal',
    sizeMb: 4.2,
    lastModified: '2026-09-18',
    department: 'Engineering',
    description: 'System microservice architecture, API gateway routing, and auth flow specs.',
    downloadCount: 42,
  },
  {
    id: 'file_roadmap_2',
    name: 'Sprint_Deliverables_Q4.docx',
    category: 'Internal',
    sizeMb: 1.8,
    lastModified: '2026-09-21',
    department: 'Product',
    description: 'Target feature timelines, release milestones, and team assignments.',
    downloadCount: 88,
  },
  {
    id: 'file_handbook_3',
    name: 'Employee_Onboarding_Handbook.pdf',
    category: 'Public',
    sizeMb: 3.5,
    lastModified: '2026-09-01',
    department: 'People Operations',
    description: 'General company policies, benefits overview, and holiday calendar.',
    downloadCount: 156,
  },
  {
    id: 'file_style_4',
    name: 'Code_Style_Guide_v3.md',
    category: 'Public',
    sizeMb: 0.4,
    lastModified: '2026-08-14',
    department: 'Engineering',
    description: 'TypeScript, Python, and CSS conventions enforced by CI linters.',
    downloadCount: 204,
  },
  {
    id: 'file_vault_pii',
    name: 'Customer_PII_Vault_2026.parquet',
    category: 'Restricted_Vault',
    sizeMb: 142.5,
    lastModified: '2026-09-22',
    department: 'Compliance',
    description: 'Encrypted customer records containing SSNs, payment card hashes, and tax IDs. STRICT RESTRICTIONS.',
    downloadCount: 1,
  },
  {
    id: 'file_vault_keys',
    name: 'AWS_Production_Keys_Backup.pem',
    category: 'Restricted_Vault',
    sizeMb: 0.2,
    lastModified: '2026-09-20',
    department: 'DevOps',
    description: 'Master root credential key pairs for cloud production VPC. Level 5 clearance required.',
    downloadCount: 0,
  },
  {
    id: 'file_conf_ma',
    name: 'Executive_M&A_Strategy_Confidential.docx',
    category: 'Confidential',
    sizeMb: 8.4,
    lastModified: '2026-09-19',
    department: 'Executive',
    description: 'Classified acquisition talks and pre-merger financial terms.',
    downloadCount: 2,
  },
  {
    id: 'file_conf_salary',
    name: 'Global_Payroll_Q3_Internal.xlsx',
    category: 'Confidential',
    sizeMb: 12.1,
    lastModified: '2026-09-15',
    department: 'Finance',
    description: 'Executive and employee compensation breakdown with stock equity vesting schedule.',
    downloadCount: 4,
  },
];

export const INITIAL_EVENTS: ActivityEvent[] = [
  {
    id: 'ev_01',
    userId: 'usr_ananya_2',
    userName: 'Ananya Rao',
    eventType: 'logon',
    timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
    ipAddress: '192.168.1.42',
    details: {
      hourOfDay: 10,
      isOffHours: false,
      reason: 'Normal morning shift logon',
    },
  },
  {
    id: 'ev_02',
    userId: 'usr_ananya_2',
    userName: 'Ananya Rao',
    eventType: 'file_read',
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    ipAddress: '192.168.1.42',
    details: {
      fileName: 'Engineering_Architecture_2026.pdf',
      fileSizeMb: 4.2,
      fileCategory: 'Internal',
    },
  },
  {
    id: 'ev_03',
    userId: 'usr_rahul_3',
    userName: 'Rahul Kumar',
    eventType: 'logon',
    timestamp: new Date(Date.now() - 2.5 * 3600000).toISOString(),
    ipAddress: '192.168.1.88',
    details: {
      hourOfDay: 11,
      isOffHours: false,
    },
  },
];

type Listener = () => void;

class ThreatStore {
  private users: User[] = [...INITIAL_USERS];
  private files: CorporateFile[] = [...INITIAL_FILES];
  private events: ActivityEvent[] = [...INITIAL_EVENTS];
  private incidents: SecurityIncident[] = [];
  private currentUserId: string = 'usr_arjun_1'; // Defaults to Lead SecOps Arjun Sharma
  private listeners: Listener[] = [];
  private connectedUsbDevices: Map<string, string[]> = new Map();

  constructor() {
    this.syncFromBackend();
  }

  // Load latest state from backend REST API
  public async syncFromBackend() {
    try {
      const [backendUsers, backendIncidents, backendEvents] = await Promise.allSettled([
        usersApi.getAll(),
        incidentsApi.getAll(),
        activityApi.getAll(),
      ]);

      if (backendUsers.status === 'fulfilled' && backendUsers.value?.length > 0) {
        this.users = backendUsers.value;
      }
      if (backendIncidents.status === 'fulfilled' && backendIncidents.value?.length > 0) {
        this.incidents = backendIncidents.value;
      }
      if (backendEvents.status === 'fulfilled' && backendEvents.value?.length > 0) {
        this.events = backendEvents.value;
      }
      this.notify();
    } catch {
      // Keep initial seed
    }
  }

  public subscribe(listener: Listener): () => void {
    this.listeners.push(listener);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== listener);
    };
  }

  private notify() {
    for (const listener of this.listeners) {
      listener();
    }
  }

  // Getters
  public getUsers(): User[] {
    return this.users;
  }

  public getUser(id: string): User | undefined {
    return this.users.find((u) => u.id === id);
  }

  public getCurrentUser(): User {
    const user = this.users.find((u) => u.id === this.currentUserId);
    return user || this.users[0];
  }

  public getFiles(): CorporateFile[] {
    return this.files;
  }

  public getEvents(userId?: string): ActivityEvent[] {
    if (userId) {
      return this.events.filter((e) => e.userId === userId);
    }
    return this.events;
  }

  public getIncidents(): SecurityIncident[] {
    return this.incidents;
  }

  public getConnectedUsbDevices(userId: string): string[] {
    return this.connectedUsbDevices.get(userId) || [];
  }

  // Actions
  public setCurrentUser(userId: string) {
    this.currentUserId = userId;
    this.notify();
  }

  public enrollFace(
    userId: string,
    embedding: number[],
    photoDataUrl?: string,
    imageFile?: Blob | File
  ) {
    const user = this.users.find((u) => u.id === userId);
    if (!user) return;
    user.enrolledFaceEmbedding = embedding;
    if (photoDataUrl) {
      user.enrolledFaceImage = photoDataUrl;
    }
    this.notify();

    // Async sync with backend
    faceApi
      .register(userId, embedding, imageFile)
      .catch((err) => console.warn('[Face API] register error:', err));
  }

  public logEvent(
    eventType: ActivityEventType,
    details: ActivityEvent['details'] = {},
    customIp?: string
  ): { event: ActivityEvent; assessment: RiskAssessment; incident?: SecurityIncident } {
    const user = this.getCurrentUser();
    const eventId = `ev_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
    const timestamp = new Date().toISOString();

    const ipAddress =
      customIp ||
      (details.isOffHours
        ? '185.220.101.5' // Foreign Tor exit node for off-hours
        : user.baseline.knownIps[0] || '192.168.1.42');

    const newEvent: ActivityEvent = {
      id: eventId,
      userId: user.id,
      userName: user.name,
      eventType,
      timestamp,
      ipAddress,
      details,
    };

    // Prepend to event stream
    this.events.unshift(newEvent);
    user.lastActive = timestamp;

    // Run dual-model ML pipeline
    const assessment = runInferencePipeline(user, this.events);

    // Update user dynamic risk
    user.currentRiskScore = assessment.compositeRiskScore;
    user.currentRiskBand = assessment.riskBand;

    let createdIncident: SecurityIncident | undefined;

    // Evaluate adaptive response triggers
    if (assessment.compositeRiskScore >= 50) {
      const existingPending = this.incidents.find(
        (i) => i.userId === user.id && i.status === 'PENDING_VERIFICATION'
      );

      if (!existingPending) {
        createdIncident = {
          id: `INC-${Date.now().toString(36).toUpperCase()}`,
          timestamp,
          userId: user.id,
          userName: user.name,
          riskScore: assessment.compositeRiskScore,
          status: 'PENDING_VERIFICATION',
          triggerEvent: `Triggered by ${eventType} (${details.fileName || details.reason || 'anomalous action'})`,
          riskBand: assessment.riskBand,
          recommendedAction: assessment.recommendedAction,
          shapSummary: assessment.shapContributions,
        };

        if (assessment.compositeRiskScore >= 80) {
          user.isRestricted = true;
          createdIncident.status = 'RESTRICTED';
        }

        this.incidents.unshift(createdIncident);
      }
    }

    this.notify();

    // Async sync with real backend
    activityApi.log(eventType, details, ipAddress).catch((err) => console.warn('[Activity API] log error:', err));

    return { event: newEvent, assessment, incident: createdIncident };
  }

  public verifyBiometricFace(
    incidentId: string,
    probeEmbedding: number[] | null,
    isTestScenarioMatch: boolean | null = null,
    imageFile?: Blob | File
  ) {
    const incident = this.incidents.find((i) => i.id === incidentId);
    if (!incident) return { success: false, reason: 'Incident not found' };

    const user = this.users.find((u) => u.id === incident.userId);
    if (!user) return { success: false, reason: 'User not found' };

    let verificationResult;

    if (isTestScenarioMatch === true) {
      verificationResult = {
        passed: true,
        confidenceScore: 0.94,
        threshold: 0.85,
        method: 'OPENCV_LBP_HISTOGRAM' as const,
        notes: 'Simulated legitimate user photo verification matched successfully (94% > 85%).',
      };
    } else if (isTestScenarioMatch === false) {
      verificationResult = {
        passed: false,
        confidenceScore: 0.38,
        threshold: 0.85,
        method: 'OPENCV_LBP_HISTOGRAM' as const,
        notes: 'Simulated impostor photo failed verification (38% < 85%).',
      };
    } else {
      if (!user.enrolledFaceEmbedding) {
        verificationResult = {
          passed: false,
          confidenceScore: 0.0,
          threshold: 0.85,
          method: 'OPENCV_LBP_HISTOGRAM' as const,
          notes: 'No registered face template found for employee profile.',
        };
      } else if (!probeEmbedding) {
        verificationResult = {
          passed: false,
          confidenceScore: 0.0,
          threshold: 0.85,
          method: 'OPENCV_LBP_HISTOGRAM' as const,
          notes: 'No probe face detected in webcam stream.',
        };
      } else {
        const res = verifyFace(probeEmbedding, user.enrolledFaceEmbedding);
        verificationResult = {
          passed: res.passed,
          confidenceScore: res.similarityScore,
          threshold: res.threshold,
          method: 'OPENCV_LBP_HISTOGRAM' as const,
          notes: res.details,
        };
      }
    }

    incident.faceVerification = {
      attemptedAt: new Date().toISOString(),
      ...verificationResult,
    };

    if (verificationResult.passed) {
      incident.status = 'ENHANCED_MONITORING';
      user.isRestricted = false;
      user.currentRiskScore = Math.min(user.currentRiskScore, 42);
      user.currentRiskBand = 'MEDIUM';
    } else {
      if (incident.riskScore >= 80) {
        incident.status = 'TERMINATED';
        user.isTerminated = true;
        user.isRestricted = true;
      } else {
        incident.status = 'RESTRICTED';
        user.isRestricted = true;
      }
    }

    this.notify();

    // Async sync with real backend
    faceApi
      .verify({
        incidentId,
        probeEmbedding: probeEmbedding || undefined,
        isTestMatch: isTestScenarioMatch !== null ? isTestScenarioMatch : undefined,
        imageFile,
      })
      .catch((err) => console.warn('[Face API] verify error:', err));

    return { success: true, verificationResult, incident };
  }

  public verifyUserFace(
    userId: string,
    probeEmbedding: number[] | null,
    incidentId?: string,
    isTestMatch: boolean | null = null,
    imageFile?: Blob | File
  ) {
    const incId =
      incidentId ||
      this.incidents.find((i) => i.userId === userId && i.status === 'PENDING_VERIFICATION')?.id;
    if (!incId) {
      return { passed: false, similarityPercentage: 0, details: 'No active verification pending' };
    }
    const result = this.verifyBiometricFace(incId, probeEmbedding, isTestMatch, imageFile);
    if (!result.success || !result.verificationResult) {
      return { passed: false, similarityPercentage: 0, details: result.reason || 'Verification failed' };
    }
    return {
      passed: result.verificationResult.passed,
      similarityPercentage: Math.round(result.verificationResult.confidenceScore * 1000) / 10,
      details: result.verificationResult.notes,
    };
  }

  public overrideIncident(
    incidentId: string,
    action: 'RESTORE_ACCESS' | 'CONFIRM_RESTRICTION' | 'TERMINATE_SESSION',
    overrideReason: string
  ) {
    const incident = this.incidents.find((i) => i.id === incidentId);
    if (!incident) return;

    const user = this.users.find((u) => u.id === incident.userId);

    incident.adminResolution = {
      resolvedBy: 'Arjun Sharma (Lead SecOps Admin)',
      resolvedAt: new Date().toISOString(),
      action,
      overrideReason,
    };

    if (action === 'RESTORE_ACCESS') {
      incident.status = 'OVERRIDDEN';
      if (user) {
        user.isRestricted = false;
        user.isTerminated = false;
        user.currentRiskScore = Math.min(user.currentRiskScore, 25);
        user.currentRiskBand = 'LOW';
      }
    } else if (action === 'CONFIRM_RESTRICTION') {
      incident.status = 'RESTRICTED';
      if (user) {
        user.isRestricted = true;
      }
    } else if (action === 'TERMINATE_SESSION') {
      incident.status = 'TERMINATED';
      if (user) {
        user.isRestricted = true;
        user.isTerminated = true;
      }
    }

    this.notify();

    // Async sync with real backend
    incidentsApi.override(incidentId, action, overrideReason).catch((err) => console.warn('[Incident API] override error:', err));
  }

  public simulateSuspiciousActivity(userId: string): SecurityIncident | null {
    const targetUser = this.users.find((u) => u.id === userId);
    if (!targetUser) return null;

    const foreignIp = '185.220.101.5';
    const now = Date.now();

    // Sequence from README:
    // 1. Multiple failed logins (3x)
    for (let i = 0; i < 3; i++) {
      this.events.unshift({
        id: `ev_sim_fail_${now}_${i}`,
        userId: targetUser.id,
        userName: targetUser.name,
        eventType: 'failed_logon',
        timestamp: new Date(now - 180000 + i * 20000).toISOString(),
        ipAddress: foreignIp,
        details: {
          reason: 'Invalid credentials entered (repeated authentication failure)',
          targetResource: 'VPN Gateway',
        },
      });
    }

    // 2. Off-hours login at 02:43 AM from unknown foreign IP
    this.events.unshift({
      id: `ev_sim_login_${now}`,
      userId: targetUser.id,
      userName: targetUser.name,
      eventType: 'logon',
      timestamp: new Date(now - 120000).toISOString(),
      ipAddress: foreignIp,
      details: {
        hourOfDay: 2,
        isOffHours: true,
        reason: 'Session initiated at 02:43 AM from unrecognized IP',
      },
    });

    // 3. Probe against AWS production keys (restricted vault)
    this.events.unshift({
      id: `ev_sim_vault_${now}`,
      userId: targetUser.id,
      userName: targetUser.name,
      eventType: 'privilege_escalation_attempt',
      timestamp: new Date(now - 60000).toISOString(),
      ipAddress: foreignIp,
      details: {
        fileName: 'AWS_Production_Keys_Backup.pem',
        fileCategory: 'Restricted_Vault',
        reason: 'Unauthorized access probe to cloud root credentials',
      },
    });

    // 4. USB removable drive connection
    this.toggleUsbDevice(targetUser.id, 'SanDisk_Cruzer_64GB');

    // 5. Large download burst (142.5 MB)
    this.events.unshift({
      id: `ev_sim_dl_${now}`,
      userId: targetUser.id,
      userName: targetUser.name,
      eventType: 'file_download',
      timestamp: new Date(now - 10000).toISOString(),
      ipAddress: foreignIp,
      details: {
        fileName: 'Customer_PII_Vault_2026.parquet',
        fileSizeMb: 142.5,
        fileCategory: 'Restricted_Vault',
        reason: 'Bulk data transfer to removable device',
      },
    });

    // Run ML inference
    const assessment = runInferencePipeline(targetUser, this.events);
    targetUser.currentRiskScore = assessment.compositeRiskScore;
    targetUser.currentRiskBand = assessment.riskBand;

    const incident: SecurityIncident = {
      id: `INC-${Date.now().toString(36).toUpperCase()}`,
      timestamp: new Date().toISOString(),
      userId: targetUser.id,
      userName: targetUser.name,
      riskScore: assessment.compositeRiskScore,
      status: 'PENDING_VERIFICATION',
      triggerEvent: `CERT-style simulated attack vector: 3 failed logins, off-hours access from foreign IP (${foreignIp}), vault key probe, and 142.5MB exfiltration burst.`,
      riskBand: assessment.riskBand,
      recommendedAction: assessment.recommendedAction,
      shapSummary: assessment.shapContributions,
    };

    if (assessment.compositeRiskScore >= 80) {
      targetUser.isRestricted = true;
    }

    this.incidents.unshift(incident);
    this.notify();

    // Async sync with real backend
    simulateApi.triggerSuspiciousActivity(userId).catch((err) => console.warn('[Simulate API] trigger error:', err));

    return incident;
  }

  public toggleUsbDevice(userId: string, deviceName = 'SanDisk_Cruzer_64GB'): boolean {
    const devices = this.connectedUsbDevices.get(userId) || [];
    let attached = false;

    if (devices.includes(deviceName)) {
      this.connectedUsbDevices.set(
        userId,
        devices.filter((d) => d !== deviceName)
      );
      attached = false;
    } else {
      this.connectedUsbDevices.set(userId, [...devices, deviceName]);
      attached = true;
    }

    const user = this.users.find((u) => u.id === userId);
    if (user) {
      const event: ActivityEvent = {
        id: `ev_usb_${Date.now()}`,
        userId: user.id,
        userName: user.name,
        eventType: 'device_connect',
        timestamp: new Date().toISOString(),
        ipAddress: user.baseline.knownIps[0] || '192.168.1.42',
        details: {
          deviceName,
          deviceType: 'USB_MASS_STORAGE',
          reason: attached ? 'Removable flash media inserted' : 'Removable media safely ejected',
        },
      };
      this.events.unshift(event);
    }

    this.notify();

    // Async sync with real backend
    hardwareApi.toggleUsb(deviceName).catch((err) => console.warn('[Hardware API] toggle error:', err));

    return attached;
  }

  public resetDemo() {
    this.users = [...INITIAL_USERS].map((u) => ({
      ...u,
      isRestricted: false,
      isTerminated: false,
      currentRiskScore: u.role === 'admin' ? 6 : 14,
      currentRiskBand: 'LOW',
    }));
    this.events = [...INITIAL_EVENTS];
    this.incidents = [];
    this.connectedUsbDevices.clear();
    this.notify();

    // Async sync with real backend
    adminApi.resetDemo().catch((err) => console.warn('[Admin API] reset error:', err));
  }
}

export const store = new ThreatStore();
